services:
  mongo:
    image: mongo:5
    container_name: todo-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  
  api:
    image: todo-backend
    build:
      context: ../backend
    container_name: todo-api
    env_file: ../backend/.env
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: ["npm", "run", "dev"]
    volumes:
      - ../backend:/app
      - /app/node_modules
#  web:
#    build:
#      context: ../frontend
#    container_name: todo-web
#    depends_on:
#      - api
#    ports:
#      - "3000:80"
volumes:
  mongo-data: